name: get_core
description: A fast develop core library use get.
version: 1.0.0
homepage: https://github.com/jonataslaw/get_storage

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  get_storage: ^2.1.1

  dio: ^5.5.0
  pretty_dio_logger: ^1.3.1

  logger: ^2.3.0
  easy_refresh: ^3.4.0

  fluttertoast: ^8.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

